name: Build when Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: git config --global user.email "aurorataro@foxmail.com"
      - run: git config --global user.name aurorataro"
      - uses: tool3/docsify-action@master
          with:
            github_token: ${{ secrets.GH_ACCESS_TOKEN }}
            branch: gh-pages